/**
 * Flow / Veo, cocuk sablonlarinda "toddler / kid / kiss / yüze dokun / skin / lips"
 * yiginini sikca "kucuklerle ilgili zararli icerik" diye reddeder.
 * Soz + yonetmen notu Flow'a gitmeden yayin-guvenli mascot diline cekilir.
 */

export const FLOW_ANIMATED_CAST_LOCK = [
  "[CAST LOCK — ANIMATED MASCOT]",
  "Every character on screen is a stylized 3D cartoon mascot animal from this film's fixed cast — no humans, no new characters.",
  "Cartoon materials only. Broadcast-safe family entertainment. Wholesome dance, gestures and prop play only.",
].join(" ");

const REPLACEMENTS: Array<[RegExp, string]> = [
  [/Tiny steam sprite/gi, "Adult cartoon steam-sprite barista"],
  [/Petite and buoyant;\s*/gi, ""],
  [/big head \(1:2\)/gi, "balanced adult-mascot proportions"],
  [/head 1:2 body/gi, "adult-mascot proportions"],
  [/\bpetite\b/gi, "compact adult"],
  [/cuddly adult voice/gi, "warm adult mascot voice"],
  [/\bcuddly\b/gi, "warm"],
  [/family-friendly/gi, "broadcast-safe"],
  [/never suddenly younger\/older/gi, "never switch singer identity"],
  [/age presentation/gi, "voice character"],
  [/exactly 1 clearly framed nose of [^,\n]+,\s*/gi, "exactly 1 playful point-to-face dance beat, "],
  [/köpükle öpücük/gi, "köpükle kalp"],
  [/kopukle opucuk/gi, "kopukle kalp"],
  [/öpücük/gi, "kalp"],
  [/opucuk/gi, "kalp"],
  [/\böpme\b/gi, "selam"],
  [/Not a toddler voice\.?/gi, "Mature, clear mascot singing voice."],
  [/never toddler baby-voice/gi, "never a thin cartoon squeak"],
  [/no toddler baby-voice/gi, "no thin cartoon squeak"],
  [/toddler baby-voice/gi, "thin cartoon squeak"],
  [/so toddlers can hear each word/gi, "so every sung word is crisp"],
  [/always readable for toddlers/gi, "always clearly readable in frame"],
  [/Clear diction for toddlers/gi, "Clear sing-along diction"],
  [/so a toddler can hum it back/gi, "so the hook is easy to hum"],
  [/\btoddlers?\b/gi, "the audience"],
  [/\bbabies\b/gi, "the audience"],
  [/\bbaby-voice\b/gi, "thin cartoon squeak"],
  [/\bbaby\b/gi, "mascot"],
  [/YouTube-kids/gi, "YouTube-family"],
  [/YouTube kids/gi, "YouTube family"],
  [/premium kids music video/gi, "premium animated music video"],
  [/kids music video/gi, "animated music video"],
  [/kids dance MV/gi, "family dance MV"],
  [/kids dance video/gi, "family dance video"],
  [/kids film equally/gi, "animated short equally"],
  [/kids film/gi, "animated short"],
  [/kids cinema/gi, "theatrical animation"],
  [/feature-quality kids/gi, "feature-quality family"],
  [/Theatrical kids-CGI/gi, "Theatrical family-CGI"],
  [/LIVELY KIDS MUSIC-VIDEO/gi, "LIVELY FAMILY MUSIC-VIDEO"],
  [/SERIAL KIDS MUSIC-VIDEO/gi, "SERIAL FAMILY MUSIC-VIDEO"],
  [/children's backing track/gi, "cheerful backing track"],
  [/\bchildren's\b/gi, "family"],
  [/child-friendly/gi, "warm and clear"],
  [/kid-eye height/gi, "eye-level camera"],
  [/Kid-safe:/gi, "Broadcast-safe:"],
  [/kid-safe/gi, "broadcast-safe"],
  [/age-safe/gi, "broadcast-safe"],
  [/age-swap/gi, "identity change"],
  [/hip sway/gi, "gentle side-to-side groove"],
  [/blowing a gentle foamy kiss/gi, "blowing a gentle foam heart bubble"],
  [/blowing foam kiss/gi, "blowing a heart-shaped foam bubble"],
  [/foamy kiss/gi, "foam heart bubble"],
  [/foam kiss/gi, "foam heart bubble"],
  [/\bat the kiss\b/gi, "beside the performer"],
  [/\bof the kiss\b/gi, "of the foam-heart beat"],
  [/\bafter the kiss\b/gi, "after the foam-heart beat"],
  [/\bat kiss\b/gi, "beside the performer"],
  [/kiss-heart/gi, "foam-heart"],
  [/kiss heart/gi, "foam heart"],
  [/\bkiss(?:es)?\b/gi, "foam-heart"],
  [/near Kokona['’]s (?:mouth|lips|cheek)/gi, "floating beside Kokona"],
  [/near the cheek/gi, "floating beside the performer"],
  [/near lips/gi, "near the performer"],
  [/near [^,]{0,40}(?:mouth|lips) at/gi, "near the performer at"],
  [/beside the cheek/gi, "beside the performer"],
  [/Cheeky smile/gi, "Playful grin"],
  [/cheeky smile/gi, "playful grin"],
  [/brows\/cheeks/gi, "brows"],
  [/pores of expression/gi, "clear expression"],
  [/true lip-sync/gi, "true syllable-sync"],
  [/accurate lip-sync/gi, "accurate syllable-sync"],
  [/full lip-sync/gi, "full syllable-sync"],
  [/lip-sync/gi, "syllable-sync"],
  [/Lip shapes must match/gi, "Singing visemes must match"],
  [/Mouth shapes, timing/gi, "Viseme timing"],
  [/Mouth shapes match/gi, "Viseme timing matches"],
  [/mouth shapes for syllables/gi, "viseme timing for syllables"],
  [/mouth shapes match every spoken syllable/gi, "viseme timing matches every spoken syllable"],
  [/silent lips/gi, "silent face"],
  [/\blips\b/gi, "visemes"],
  [/sweat\/skin sheen/gi, "material sheen"],
  [/skin\/ears\/fur/gi, "surface/ears/fur"],
  [/fur\/skin palette/gi, "fur/surface palette"],
  [/fur\/skin pattern/gi, "fur/surface pattern"],
  [/fur\/skin colors/gi, "fur/surface colors"],
  [/skin-pore/gi, "surface-detail"],
  [/photographic skin texture/gi, "photographic surface texture"],
  [/skin texture visible/gi, "material texture visible"],
  [/skin texture/gi, "surface texture"],
  [/skin tone/gi, "surface tone"],
  [/skin oil/gi, "surface sheen"],
  [/skin shows pores/gi, "surface shows fine detail"],
  [/\bskins?\b/gi, "surface"],
  [/photoreal humans are forbidden\.?/gi, "Cartoon materials only."],
  [/Photoreal humans are forbidden\.?/gi, "Cartoon materials only."],
  [/photorealistic/gi, "high-detail stylized"],
  [/playful nose-point beat(?:ed)? by [^,]{0,50}fingertip/gi, "playful nose-point dance"],
  [/nose[^\n.]{0,40}fingertip/gi, "playful nose-point dance"],
  [/fingertip[^\n.]{0,40}nose/gi, "playful nose-point dance"],
  [/nose boop/gi, "playful nose-point beat"],
  [/booping her nose/gi, "pointing to her own nose"],
  [/booping his nose/gi, "pointing to his own nose"],
  [/\bbooping\b/gi, "pointing"],
  [/\bboops\b/gi, "points"],
  [/\bboop(?:ed)?\b/gi, "point"],
  [/fingertip boops her nose/gi, "points to her own nose on the beat"],
  [/booped by [^,]{0,40}fingertip/gi, "indicated with a playful point"],
  [/nose clearly touched by [^,]{0,60}fingertip/gi, "nose indicated with a playful point"],
  [/touched by her fingertip/gi, "indicated with a playful point"],
  [/touched by his fingertip/gi, "indicated with a playful point"],
  [/touches her nose/gi, "points to her own nose on the beat"],
  [/touches his nose/gi, "points to his own nose on the beat"],
  [/işaret parmağıyla buruna/gi, "ritimle burnunu işaret ederek"],
  [/parmağıyla buruna/gi, "burnunu işaret ederek"],
  [/burnuna dokunarak/gi, "burnunu işaret ederek"],
  [/buruna hızlı/gi, "burnunu hızlı işaret"],
  [/Touch Your Nose/gi, "Point to Your Nose"],
  [/clearly framed nose of\s+([^,]+),\s*touched/gi, "playful nose-point dance by $1,"],
  [/patio kids['’]? silhouettes/gi, "patio guest silhouettes"],
  [/kids['’]? silhouettes/gi, "guest silhouettes"],
  [/kid[-\u2011\u2010\u2013\u2014]choir/gi, "group-harmony"],
  [/kid choir/gi, "group harmony"],
  [/kids choir/gi, "group harmony"],
  [/burnuna hafifce dokun/gi, "burnunu ritimle isaret et"],
  [/burnuna hafifçe dokun/gi, "burnunu ritimle işaret et"],
  [/human kids/gi, "background extras"],
  [/chalkboard menu/gi, "blank chalkboard with decorative swirls and no letters"],
  [/chalk menu/gi, "blank chalkboard with decorative swirls and no letters"],
  [/3D CGI kids animation/gi, "3D CGI family animation"],
  [/Feature-film kids animation/gi, "Feature-film family animation"],
  [/\bkids-pop\b/gi, "bright pop"],
  [/\bkids party\b/gi, "family party"],
  [/\bkids MV\b/gi, "family MV"],
  [/\bkids\b/gi, "family"],
  [/\bkid\b/gi, "family"],
  [/\bchildren\b/gi, "the audience"],
  [/\bchild\b/gi, "character"],
  [/\binfants?\b/gi, "the audience"],
];

/** Yonetmen + soz metnini Flow politika süzgecinden gecirir (tirnak icindeki sozler dahil). */
export function sanitizeKidsPromptForFlow(prompt: string): string {
  let out = prompt;
  for (const [pattern, replacement] of REPLACEMENTS) {
    out = out.replace(pattern, replacement);
  }
  return out;
}

/** CAST LOCK'u @referanslarin hemen altina yerlestirir; yoksa ekler. */
export function ensureAnimatedCastLock(prompt: string, maxChars = 6_000): string {
  if (/\[CAST LOCK — ANIMATED MASCOT\]/i.test(prompt)) {
    return prompt.slice(0, maxChars);
  }
  const atRefs = prompt.match(/^(?:@[^\n]+\n)+/);
  const lock = FLOW_ANIMATED_CAST_LOCK;
  const next = atRefs
    ? `${atRefs[0]}${lock}\n\n${prompt.slice(atRefs[0].length).replace(/^\n+/, "")}`
    : `${lock}\n\n${prompt}`;
  return next.slice(0, maxChars);
}
