"""
Bölüm 7.5: 16 Niş Üretim Profili ve Stil Motoru (Niche Production Profiles & Style Engine)
16 temel Shorts nişi için optimize edilmiş görsel motifler, anlatıcı tonları, altyazı şablonları,
müzik ritim eşlemeleri ve viral kanca parametreleri.
"""
from typing import Dict, Any, List, Optional
import re

# 16 Standart Üretim Profili
NICHE_16_PROFILES: Dict[str, Dict[str, Any]] = {
    "1_news_flash": {
        "niche_id": "1_news_flash",
        "name_tr": "Haber ve Gündem",
        "name_en": "Breaking News Flash",
        "category": "Haber & Güncel",
        "tone": "urgent, factual, authoritative, fast-paced",
        "hook_style": "SON DAKİKA! Bu haber her şeyi değiştirebilir!",
        "visual_motif": "breaking_news",
        "visual_subjects": [
            "city skyline night timelapse",
            "newsroom desk papers",
            "crowd street protest aerial",
            "breaking news studio lights",
            "financial district traffic blur",
        ],
        "must_include": ["city", "news", "crowd", "studio"],
        "must_exclude": ["horror skull", "ufo alien", "bright beach cartoon"],
        "subtitle_preset": "high_contrast_retention",
        "bgm_mood": "news",
        "target_bpm": 120.0,
        "retention_pacing": "fast (2.0-3.0s cuts)",
        "preferred_hook_type": "Shock Stat",
    },
    "2_philosophy_stoic": {
        "niche_id": "2_philosophy_stoic",
        "name_tr": "Felsefe ve Stoacılık",
        "name_en": "Stoic Philosophy & Wisdom",
        "category": "Felsefe & Kişisel Gelişim",
        "tone": "calm, contemplative, profound, commanding",
        "hook_style": "Bunu öğrenene kadar hayatınızı yanlış yaşıyordunuz...",
        "visual_motif": "imperial_rome",
        "visual_subjects": [
            "bronze marcus aurelius statue",
            "ancient roman marble columns",
            "old parchment scroll torchlight",
            "stoic philosopher reading alone",
            "calm ocean horizon sunrise",
            "candle flame dark room",
        ],
        "must_include": ["marble", "rome", "scroll", "statue", "torch", "philosopher"],
        "must_exclude": ["skull", "ufo", "horror", "blood", "party", "modern tech"],
        "subtitle_preset": "wisdom_emerald",
        "bgm_mood": "calm",
        "target_bpm": 78.0,
        "retention_pacing": "deep (3.5-5.0s cuts)",
        "preferred_hook_type": "Cognitive Dissonance",
    },
    "3_bizarre_history": {
        "niche_id": "3_bizarre_history",
        "name_tr": "Tuhaf Tarih Olayları",
        "name_en": "Bizarre Historical Events",
        "category": "Tarih & Gizem",
        "tone": "mysterious, narrative, intriguing, suspenseful",
        "hook_style": "Tarih kitaplarının sizden sakladığı o akılalmaz olay...",
        "visual_motif": "bizarre_history",
        "visual_subjects": [
            "sepia ancient artifact closeup",
            "vintage archival photograph",
            "victorian cobblestone street fog",
            "ancient tomb discovery torchlight",
            "old parchment secret map",
            "steampunk brass mechanism",
        ],
        "must_include": ["vintage", "history", "ancient", "archive", "parchment"],
        "must_exclude": ["modern smartphone", "cyberpunk neon", "supercar"],
        "subtitle_preset": "history_sepia",
        "bgm_mood": "dramatic",
        "target_bpm": 85.0,
        "retention_pacing": "moderate (3.0-4.0s cuts)",
        "preferred_hook_type": "Curiosity Gap",
    },
    "4_ai_money_tech": {
        "niche_id": "4_ai_money_tech",
        "name_tr": "Yapay Zeka ve Finans",
        "name_en": "AI, Money & Future Tech",
        "category": "Teknoloji & Finans",
        "tone": "visionary, analytical, high-tech, urgent",
        "hook_style": "Yapay zekanın bu özelliğini bilenler günde binlerce dolar kazanıyor...",
        "visual_motif": "ai_future_tech",
        "visual_subjects": [
            "neural network glowing nodes digital",
            "robotic humanoid hand precision",
            "data center servers blinking lights",
            "quantum computer circuit board",
            "abstract code matrix stream green",
            "cyberpunk holographic interface",
        ],
        "must_include": ["ai", "digital", "tech", "network", "code", "futuristic"],
        "must_exclude": ["ancient rome", "medieval armor", "farm nature"],
        "subtitle_preset": "cyber_green",
        "bgm_mood": "energetic",
        "target_bpm": 115.0,
        "retention_pacing": "fast (2.2-3.2s cuts)",
        "preferred_hook_type": "Curiosity Gap",
    },
    "5_luxury_lifestyle": {
        "niche_id": "5_luxury_lifestyle",
        "name_tr": "Lüks Yaşam ve Başarı",
        "name_en": "Luxury Lifestyle & Elite Wealth",
        "category": "Yaşam & Başarı",
        "tone": "sophisticated, aspirational, confident, prestigious",
        "hook_style": "Milyarderlerin kimseye söylemediği o tek kural...",
        "visual_motif": "ultra_luxury",
        "visual_subjects": [
            "private jet interior penthouse view",
            "luxury yacht mediterranean sunset",
            "carbon fiber supercar driving city",
            "high end gold wristwatch detail",
            "marble villa infinity pool dusk",
            "expensive champagne celebration",
        ],
        "must_include": ["luxury", "penthouse", "supercar", "yacht", "mansion", "gold"],
        "must_exclude": ["dirty street", "ruins", "horror", "cheap plastic"],
        "subtitle_preset": "luxury_elegance",
        "bgm_mood": "lofi",
        "target_bpm": 90.0,
        "retention_pacing": "aesthetic (3.0-4.5s cuts)",
        "preferred_hook_type": "Curiosity Gap",
    },
    "6_psychology_tricks": {
        "niche_id": "6_psychology_tricks",
        "name_tr": "Psikoloji Taktikleri",
        "name_en": "Dark Psychology & Mind Hacks",
        "category": "Psikoloji & Manipülasyon",
        "tone": "whispering, manipulative, intense, psychological",
        "hook_style": "Birinin yalan söylediğini anlamanın kanıtlanmış tek yolu...",
        "visual_motif": "mind_shadow",
        "visual_subjects": [
            "silhouette of person in doorway",
            "chess board strategic move closeup",
            "mirror reflection distorted dark",
            "neon rain reflections city night",
            "subtle eye contact extreme closeup",
        ],
        "must_include": ["silhouette", "mirror", "shadow", "chess", "reflection"],
        "must_exclude": ["cartoon kids", "bright comedy", "sunny beach"],
        "subtitle_preset": "psychology_violet",
        "bgm_mood": "mysterious",
        "target_bpm": 80.0,
        "retention_pacing": "rhythmic (2.5-3.8s cuts)",
        "preferred_hook_type": "Problem-Agitation",
    },
    "7_space_cosmos": {
        "niche_id": "7_space_cosmos",
        "name_tr": "Uzay ve Kozmoloji",
        "name_en": "Space, Cosmos & Astronomy",
        "category": "Bilim & Uzay",
        "tone": "awe-inspiring, cosmic, cinematic, humbling",
        "hook_style": "Evrenin sınırında öyle bir şey bulundu ki tüm fizik kuralları çöktü...",
        "visual_motif": "deep_space",
        "visual_subjects": [
            "james webb nebula galaxy colors",
            "black hole accretion disk simulation",
            "solar flare sun surface telescope",
            "astronaut spacewalk earth background",
            "saturn rings close up majestic",
            "star cluster deep void darkness",
        ],
        "must_include": ["space", "galaxy", "nebula", "planet", "cosmos", "stars"],
        "must_exclude": ["office desk", "living room", "traffic street"],
        "subtitle_preset": "space_neon_blue",
        "bgm_mood": "ambient",
        "target_bpm": 82.0,
        "retention_pacing": "cinematic (3.0-4.5s cuts)",
        "preferred_hook_type": "Cognitive Dissonance",
    },
    "8_survival_myth": {
        "niche_id": "8_survival_myth",
        "name_tr": "Hayatta Kalma Efsaneleri",
        "name_en": "Survival Myths & Extreme Situations",
        "category": "Macera & Doğa",
        "tone": "gripping, urgent, practical, breathless",
        "hook_style": "Filmlerde gördüğünüz bu hayatta kalma taktiği aslında sizi öldürür!",
        "visual_motif": "wilderness_survival",
        "visual_subjects": [
            "campfire night wilderness forest",
            "blizzard mountain peak climber",
            "deep jungle river crossing danger",
            "desert dunes mirage scorching sun",
            "survival knife carving wood",
            "raging ocean storm waves boat",
        ],
        "must_include": ["survival", "forest", "wild", "mountain", "nature", "fire"],
        "must_exclude": ["city office", "neon club", "shopping mall"],
        "subtitle_preset": "red_fire",
        "bgm_mood": "dramatic",
        "target_bpm": 105.0,
        "retention_pacing": "dynamic (2.2-3.4s cuts)",
        "preferred_hook_type": "Cognitive Dissonance",
    },
    "9_five_facts": {
        "niche_id": "9_five_facts",
        "name_tr": "5 İlginç Gerçek",
        "name_en": "5 Mind-Blowing Facts",
        "category": "Eğlence & Bilgi",
        "tone": "entertaining, curious, fast, engaging",
        "hook_style": "Beyninizin bu bilgiyi duyduktan sonra asla eskisi gibi olmayacak 5 gerçek!",
        "visual_motif": "classroom_science",
        "visual_subjects": [
            "frozen lake iceberg winter blue",
            "honey jar dripping macro closeup",
            "classroom anatomical model",
            "deep ocean creatures glowing",
            "lightning bolt striking night",
        ],
        "must_include": ["science", "nature", "macro", "animal"],
        "must_exclude": ["horror", "skull", "ghost", "bitcoin"],
        "subtitle_preset": "mrbeast_style",
        "bgm_mood": "quiz",
        "target_bpm": 110.0,
        "retention_pacing": "snappy (2.0-3.0s cuts)",
        "preferred_hook_type": "Curiosity Gap",
    },
    "10_fitness_biohack": {
        "niche_id": "10_fitness_biohack",
        "name_tr": "Biyolojik Gelişim ve Fitness",
        "name_en": "Fitness, Biohacking & Longevity",
        "category": "Sağlık & Spor",
        "tone": "energetic, motivating, intense, scientific",
        "hook_style": "Sürekli yorgun uyanıyorsanız sebebi düşündüğünüz şey değil...",
        "visual_motif": "athletic_performance",
        "visual_subjects": [
            "sweat dripping athlete barbell deadlift",
            "sprinting track slow motion muscles",
            "cold plunge ice bath recovery",
            "dna helix biotechnology render",
            "heart rate monitor pulse data",
            "boxing heavy bag power impact",
        ],
        "must_include": ["fitness", "athlete", "muscle", "workout", "gym", "biohack"],
        "must_exclude": ["fast food burger", "couch potato", "ancient scroll"],
        "subtitle_preset": "fitness_punch",
        "bgm_mood": "energetic",
        "target_bpm": 120.0,
        "retention_pacing": "punchy (2.0-3.0s cuts)",
        "preferred_hook_type": "Problem-Agitation",
    },
    "11_reddit_stories": {
        "niche_id": "11_reddit_stories",
        "name_tr": "Reddit İtirafları ve Hikayeler",
        "name_en": "Reddit Stories & Confessions",
        "category": "Hikaye & Yaşam",
        "tone": "conversational, suspenseful, raw, emotional",
        "hook_style": "Düğün günümde kayınvalidemin telefonunda gördüğüm mesaj her şeyi yıktı...",
        "visual_motif": "relatable_drama",
        "visual_subjects": [
            "hands typing on smartphone glowing screen",
            "person sitting head in hands emotional",
            "dark bedroom looking out window rain",
            "subway train commute reflection",
            "whispering secret shadow silhouette",
        ],
        "must_include": ["smartphone", "person", "shadow", "reflection", "rain"],
        "must_exclude": ["ancient rome", "space nebula", "supercar"],
        "subtitle_preset": "tiktok_bold",
        "bgm_mood": "mysterious",
        "target_bpm": 85.0,
        "retention_pacing": "dramatic (2.5-3.8s cuts)",
        "preferred_hook_type": "Curiosity Gap",
    },
    "12_amazon_affiliate": {
        "niche_id": "12_amazon_affiliate",
        "name_tr": "Ürün İnceleme ve Satış Ortaklığı",
        "name_en": "Amazon Viral Gadgets & Affiliate",
        "category": "E-Ticaret & Ürünler",
        "tone": "practical, exciting, problem-solving, satisfying",
        "hook_style": "Bunu neden daha önce almadım diyeceğiniz 3 akıllı ürün...",
        "visual_motif": "smart_gadget_review",
        "visual_subjects": [
            "sleek ergonomic desk setup clean",
            "unboxing tech gadget hands closeup",
            "smart home automation device glowing",
            "portable lifestyle everyday carry",
            "aesthetic kitchen gadget demo",
        ],
        "must_include": ["gadget", "desk", "tech", "device", "lifestyle", "clean"],
        "must_exclude": ["horror skull", "blood", "ancient ruin"],
        "subtitle_preset": "capcut_yellow",
        "bgm_mood": "lofi",
        "target_bpm": 100.0,
        "retention_pacing": "smooth (2.5-3.5s cuts)",
        "preferred_hook_type": "Problem-Agitation",
    },
    "13_crypto_finance": {
        "niche_id": "13_crypto_finance",
        "name_tr": "Kripto ve Borsa",
        "name_en": "Crypto, Bitcoin & Trading",
        "category": "Finans & Yatırım",
        "tone": "tense, alert, high-stakes, analytical",
        "hook_style": "Balinalar bu gece cüzdanlarını boşaltıyor — işte büyük çöküşün sebebi!",
        "visual_motif": "finance_pulse",
        "visual_subjects": [
            "stock chart candlestick screen red green",
            "bitcoin gold coin close up metallic",
            "trading desk multiple monitors live",
            "city financial district aerial dusk",
            "blockchain cyber network grid",
        ],
        "must_include": ["chart", "coin", "market", "trading", "bitcoin"],
        "must_exclude": ["horror skull", "farm nature", "kids"],
        "subtitle_preset": "crypto_gold",
        "bgm_mood": "energetic",
        "target_bpm": 115.0,
        "retention_pacing": "fast (2.0-3.0s cuts)",
        "preferred_hook_type": "Shock Stat",
    },
    "14_mysterious_cases": {
        "niche_id": "14_mysterious_cases",
        "name_tr": "Gizemli Olaylar ve Suç",
        "name_en": "Mysterious Cases & True Crime",
        "category": "Gizem & Suç",
        "tone": "chilling, investigative, somber, thrilling",
        "hook_style": "Polis olay yerine girdiğinde evde hiçbir şey eksik değildi, bir kişi hariç...",
        "visual_motif": "dark_archive",
        "visual_subjects": [
            "foggy dark forest night cinematic",
            "abandoned archive case files dust",
            "police tape fluttering street light",
            "dark corridor flickering bulb",
            "vintage typewriter investigation notes",
        ],
        "must_include": ["fog", "shadow", "archive", "mystery", "police"],
        "must_exclude": ["bright beach", "cartoon comedy", "sunny day"],
        "subtitle_preset": "horror_blood",
        "bgm_mood": "mysterious",
        "target_bpm": 78.0,
        "retention_pacing": "suspenseful (3.0-4.5s cuts)",
        "preferred_hook_type": "Curiosity Gap",
    },
    "15_parenting_hacks": {
        "niche_id": "15_parenting_hacks",
        "name_tr": "Ebeveynlik İpuçları",
        "name_en": "Parenting Hacks & Child Psychology",
        "category": "Aile & Çocuk",
        "tone": "warm, empathetic, practical, reassuring",
        "hook_style": "Çocuğunuza asla söylememeniz gereken o 3 masum kelime...",
        "visual_motif": "family_comfort",
        "visual_subjects": [
            "parent toddler learning blocks colorful",
            "baby sleeping peacefully soft lighting",
            "family kitchen healthy breakfast",
            "creative sensory toy child hands",
            "sunny nursery organized shelves calm",
        ],
        "must_include": ["family", "baby", "parent", "child", "home", "warm"],
        "must_exclude": ["horror skull", "blood", "nightclub", "cyberpunk"],
        "subtitle_preset": "clean_white",
        "bgm_mood": "calm",
        "target_bpm": 90.0,
        "retention_pacing": "gentle (3.0-4.0s cuts)",
        "preferred_hook_type": "Problem-Agitation",
    },
    "16_islamic_wisdom": {
        "niche_id": "16_islamic_wisdom",
        "name_tr": "Maneviyat ve Hikmetli Sözler",
        "name_en": "Islamic Wisdom & Sacred Quotes",
        "category": "Maneviyat & Din",
        "tone": "reverent, peaceful, inspiring, spiritual",
        "hook_style": "Peygamber Efendimiz bu duayı her sabah okurdu...",
        "visual_motif": "islamic_devotion",
        "visual_subjects": [
            "mosque dome golden sunrise morning",
            "open quran pages soft sunlight",
            "prayer hands raised dusk peaceful",
            "islamic geometric calligraphy gold",
            "dark blue satin silk flow slow motion",
            "minaret silhouette dawn horizon",
        ],
        "must_include": ["mosque", "quran", "prayer", "calligraphy", "sunrise", "silk"],
        "must_exclude": [
            "statue", "idol", "marcus aurelius", "colosseum", "alcohol",
            "wine", "beer", "pig", "pork", "prophet face",
        ],
        "subtitle_preset": "wisdom_emerald",
        "bgm_mood": "calm",
        "target_bpm": 78.0,
        "retention_pacing": "contemplative (3.5-5.0s cuts)",
        "preferred_hook_type": "Curiosity Gap",
    },
}

# Plan/Director Alias Haritası (16 nişin tüm eşanlamlıları)
NICHE_CANONICAL_MAP: Dict[str, str] = {
    # 1. Haber
    "1_news_flash": "1_news_flash",
    "news": "1_news_flash",
    "haber": "1_news_flash",
    "breaking": "1_news_flash",
    # 2. Felsefe
    "2_philosophy_stoic": "2_philosophy_stoic",
    "6_stoic_philosophy": "2_philosophy_stoic",
    "stoic_philosophy": "2_philosophy_stoic",
    "stoic": "2_philosophy_stoic",
    "philosophy": "2_philosophy_stoic",
    "felsefe": "2_philosophy_stoic",
    # 3. Tuhaf Tarih
    "3_bizarre_history": "3_bizarre_history",
    "19_historical_battles": "3_bizarre_history",
    "history": "3_bizarre_history",
    "tarih": "3_bizarre_history",
    # 4. Yapay Zeka & Para
    "4_ai_money_tech": "4_ai_money_tech",
    "21_ai_tools_hacks": "4_ai_money_tech",
    "ai_tools": "4_ai_money_tech",
    "ai": "4_ai_money_tech",
    "tech": "4_ai_money_tech",
    # 5. Lüks Yaşam
    "5_luxury_lifestyle": "5_luxury_lifestyle",
    "16_wealth_entrepreneurship": "5_luxury_lifestyle",
    "31_supercars_automotive": "5_luxury_lifestyle",
    "luxury": "5_luxury_lifestyle",
    "wealth": "5_luxury_lifestyle",
    # 6. Psikoloji Taktikleri
    "6_psychology_tricks": "6_psychology_tricks",
    "7_dark_psychology": "6_psychology_tricks",
    "psychology": "6_psychology_tricks",
    "karanlik_psikoloji": "6_psychology_tricks",
    # 7. Uzay
    "7_space_cosmos": "7_space_cosmos",
    "space": "7_space_cosmos",
    "cosmos": "7_space_cosmos",
    "uzay": "7_space_cosmos",
    # 8. Hayatta Kalma
    "8_survival_myth": "8_survival_myth",
    "26_dangerous_places": "8_survival_myth",
    "27_common_myths_busted": "8_survival_myth",
    "survival": "8_survival_myth",
    "hayatta_kalma": "8_survival_myth",
    # 9. 5 Gerçek
    "9_five_facts": "9_five_facts",
    "facts": "9_five_facts",
    "gercekler": "9_five_facts",
    # 10. Fitness
    "10_fitness_biohack": "10_fitness_biohack",
    "23_fitness_nutrition_hacks": "10_fitness_biohack",
    "fitness": "10_fitness_biohack",
    "biohack": "10_fitness_biohack",
    # 11. Reddit Hikayeleri
    "11_reddit_stories": "11_reddit_stories",
    "2_reddit_confessions": "11_reddit_stories",
    "reddit": "11_reddit_stories",
    "itiraf": "11_reddit_stories",
    # 12. Amazon Satış Ortaklığı
    "12_amazon_affiliate": "12_amazon_affiliate",
    "affiliate": "12_amazon_affiliate",
    "amazon": "12_amazon_affiliate",
    "urun": "12_amazon_affiliate",
    # 13. Kripto
    "13_crypto_finance": "13_crypto_finance",
    "8_crypto_market": "13_crypto_finance",
    "crypto_finance": "13_crypto_finance",
    "crypto": "13_crypto_finance",
    "bitcoin": "13_crypto_finance",
    # 14. Gizemli Olaylar & Korku
    "14_mysterious_cases": "14_mysterious_cases",
    "13_mystery_paranormal": "14_mysterious_cases",
    "dark_horror_cases": "14_mysterious_cases",
    "horror": "14_mysterious_cases",
    "korku": "14_mysterious_cases",
    "crime": "14_mysterious_cases",
    "mystery": "14_mysterious_cases",
    "gizem": "14_mysterious_cases",
    # 15. Ebeveynlik
    "15_parenting_hacks": "15_parenting_hacks",
    "33_parenting_child_hacks": "15_parenting_hacks",
    "parenting": "15_parenting_hacks",
    "ebeveyn": "15_parenting_hacks",
    # 16. Maneviyat & Hikmet
    "16_islamic_wisdom": "16_islamic_wisdom",
    "10_religious_quotes": "16_islamic_wisdom",
    "islamic": "16_islamic_wisdom",
    "dini": "16_islamic_wisdom",
    "hadis": "16_islamic_wisdom",
}


def resolve_niche_profile(niche_key: str = "") -> Dict[str, Any]:
    """
    Girilen niş anahtarını 16 üretim profilinden birine çözümler.
    Varsayılan: 1_news_flash.
    """
    key = str(niche_key or "").strip().lower()
    
    # 1. Doğrudan veya canonical map eşleşmesi
    canon = NICHE_CANONICAL_MAP.get(key)
    if canon and canon in NICHE_16_PROFILES:
        return dict(NICHE_16_PROFILES[canon])

    # 2. Alt kelime eşleşmesi
    for alias, target in NICHE_CANONICAL_MAP.items():
        if alias in key or key in alias:
            return dict(NICHE_16_PROFILES[target])

    return dict(NICHE_16_PROFILES["1_news_flash"])


def list_niche_profiles() -> List[Dict[str, Any]]:
    """16 standart niş profilinin listesini döndürür."""
    return [dict(v) for v in NICHE_16_PROFILES.values()]
